
function(find_files FINDED_FILES DIR)
  set(RESULT)
  foreach(EXTR ${ARGN})
    file(GLOB_RECURSE FILES ${DIR}/${EXTR})
    list(APPEND RESULT ${FILES})
  endforeach()
  set(${FINDED_FILES} ${RESULT} PARENT_SCOPE)
endfunction()

function(find_project_files SRC_FILES DIR)
  set(FILTER *.asm *.nasm *.S *.cpp *.cxx *.cu *.c *.cc *.h *.cuh *.hpp *.qrc *.qss)
  if(WIN32)
    list(APPEND FILTER *.rc)
  endif()
  if (UNIX)
    list(APPEND FILTER *.ASM *.NASM *.CPP *.CXX *.CU *.C *.CC *.H *.CUH *.HPP)
  endif()
  find_files(FINDED_FILES ${DIR} ${FILTER})
  set(${SRC_FILES} ${FINDED_FILES} PARENT_SCOPE)
endfunction()

function(find_ui_files UI_FILES DIR)
  set(FILTER *.ui)
  find_files(FINDED_FILES ${DIR} ${FILTER})
  set(${UI_FILES} ${FINDED_FILES} PARENT_SCOPE)
endfunction()
